language: objective-c
matrix:
  include:
    - language: cpp
      os: osx

before_install:
  - brew tap david0/homebrew-audio 
  - brew update

script:
  - brew install -v `grep -l url Formula/*.rb|grep -v joeboy`
  - brew test `grep -l url Formula/*.rb|grep -v joeboy`
  - brew install -v --HEAD `grep -l head Formula/*.rb`
  - brew test `grep -l head Formula/*.rb`



notifications:
  email:
    on_success: never
    on_failure: always
