language: objective-c
matrix:
  include:
    - env: OSX=10.11
      os: osx
      osx_image: osx10.11
      rvm: system
    - env: OSX=10.10
      os: osx
      osx_image: xcode7
      rvm: system
    - env: OSX=10.9
      os: osx
      osx_image: beta-xcode6.2
      rvm: system

before_install:
  - brew tap david0/homebrew-audio 
  - brew update

script:
  - brew install `basename -s .rb Formula/*.rb`
  - brew test `basename -s .rb Formula/*.rb`


notifications:
  email:
    on_success: never
    on_failure: always
